export BUILDS_DIR=/home/cmann/builds
export MPI_PATH=/usr/mpi/gcc/openmpi-4.1.4-hfi
export IMB_DIR=/home/cmann/code/mpi-benchmarks-internal
export LOG_DIR=/tmp/runout
export MPI_PROGRAMS=/home/cmann/mpi-programs
export LIBFAB_DIR=/home/cmann/code/libfabric-internal
export LIBFABDEVEL_DIR=/home/cmann/code/libfabric-devel
export LIBFAB_PATH=$BUILDS_DIR/libfabric.debug
#export LIBFAB_PATH=$BUILDS_DIR/libfabric.optimized
export FI_OPX_EXPECTED_RECEIVE_ENABLE=1
export TIDFLOW_SET=0
# export SIGHANDLER_PATH=$LIBFABDEVEL_DIR/debug/handlers/segfault_abort_handler.so
