export BUILDS_DIR=/home/cmann/builds
export MPI_PATH=/usr/mpi/gcc/openmpi-4.1.4-hfi
export IMB_DIR=/home/cmann/code/mpi-benchmarks-internal
export LOG_DIR=/tmp/runout
export MPI_PROGRAMS=/home/cmann/mpi-programs
export LIBFAB_DIR=/home/cmann/code/libfabric-internal
export LIBFABDEVEL_DIR=/home/cmann/code/libfabric-devel
export LIBFAB_PATH=$BUILDS_DIR/libfabric.debug
# export LIBFAB_PATH=$BUILDS_DIR/libfabric.optimized
# export SEGFAULT_HDLR="/opx-dev/debug/handlers/segfault_handler.so"
# export ABORT_HDLR="/opx-dev/debug/handlers/abort_handler.so"
# export SEG_ABORT_HDLR="/opx-dev/debug/handlers/segfault_abort_handler.so"
